In [1]:
import numpy as np

In [4]:
# 2. check numpy version
print(np.__version__)

1.16.3


In [6]:
# 3. null vectors
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
# 4. find the memory size of array
z = np.zeros((10,10))
print(f'{z.size * z.itemsize} bytes')

800 bytes


In [12]:
# 6. Change the value of array
z = np.zeros(10)
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [13]:
# 7. Create a vector with values ranging from 10 to 49
z = np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [14]:
# 8. Reverse a vector
z = np.arange(50)
z = z[::-1]
print(z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [17]:
# 9. Create 3*3 matrix with values ranging from 0 to 8
z = np.arange(9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [19]:
# 10. Find incides of non-zero elements from [1,2,0,0,4,0]
nz = np.nonzero([1,2,0,0,4,0])
print(nz)  # nonzero인 value를 출력

(array([0, 1, 4]),)


In [20]:
# 11. Create a 3*3 identity matrix
z = np.eye(3)
print(z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
# 12. Create a 3*3*3 array with random values
z = np.random.random((3,3,3))  # random함수 : 0~1사이 num출력
print(z)

[[[0.97710951 0.12984091 0.78136811]
  [0.95059233 0.46791681 0.90311312]
  [0.69832962 0.79277187 0.91883655]]

 [[0.94563656 0.01120254 0.33868121]
  [0.79761456 0.33114411 0.42723396]
  [0.18141607 0.87912252 0.66386467]]

 [[0.80372222 0.48780975 0.804823  ]
  [0.47330972 0.78176695 0.94892052]
  [0.48831487 0.4489671  0.59317739]]]


In [30]:
# 13. Create a 10*10 array with random values and find the minimum and maximum values
z = np.random.random((10, 10))
print(z.min(), z.max())

0.01810533910168688 0.9933312880782608


In [29]:
# 14. Create a random vector of size 30 and find the mean value
z = np.random.random(30)
print(z.mean())

0.5247584470306141


In [28]:
# 15. Create a 2d array with 1 on the border and 0 inside
z = np.ones((10, 10))
z[1:-1, 1:-1] = 0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [31]:
# 16. How to add a border (filled with 0's) around an existing array?
z = np.ones((5,5))
z = np.pad(z, pad_width=1, mode='constant', constant_values=0)
print(z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [40]:
# 17. What is the result of the following expression? (수학 문제)
# np.inf: 무한대,  np.nan: 정의할 수 없는 숫자
print(0 * np.nan)       # 정의 할 수 없는 수열 * 0 = 정의 할 수 없는 수열
print(np.nan == np.nan) # 정의 할 수 없는 수열과는 비교 불가능
print(np.inf > np.nan)  # 정의 할 수 없는 수열 과는 비교 불가능
print(np.nan - np.nan)  # 정의 할 수 없는 수열 - 정의할 수 없는 수열
print(np.nan in set([np.nan]))  # nan인 배열들의 집합 안에 있음
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [48]:
# 18. Create a 5*5 matrix with values 1,2,3,4 fust below the diagonal
z = np.diag(np.arange(4)+1, k=-1)  # np.diag method 안의 변수 설정
print(z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [49]:
# 19. Create a 8*8 matrix and fill it with a checkerboard pattern
z = np.zeros((8,8))
z[1::2, ::2] = 1
z[::2, 1::2] = 1
print(z)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]
