In [1]:
import numpy as np

In [6]:
ls = [1,2,3,4,5]
print("before : {}".format(ls))
for idx in range(len(ls)):
    ls[idx] = ls[idx] * 3
print("after : {}".format(ls))

before : [1, 2, 3, 4, 5]
after : [3, 6, 9, 12, 15]


In [7]:
na = np.array(ls)
na*=3
print(type(na), na)

<class 'numpy.ndarray'> [ 9 18 27 36 45]


In [8]:
na_2 = np.array([6,7,8,9,10])
result = na * na_2
print("{}\n{}\n{}".format(na, na_2, result))

[ 9 18 27 36 45]
[ 6  7  8  9 10]
[ 54 126 216 324 450]


In [9]:
na ==9, na >30

(array([ True, False, False, False, False], dtype=bool),
 array([False, False, False,  True,  True], dtype=bool))

In [10]:
idx = na_2 % 3 ==0
print(idx)

[ True False False  True False]


In [12]:
print(na_2[idx])

[6 9]


In [13]:
na1= np.array([1,2,3,4,5])
na2 = np.array([1,3,3,4,4])
print(na1 == na2)
print(na1[na1 == na2])

[ True False  True  True False]
[1 3 4]


In [14]:
print(na1[na1>=na2])

[1 3 4 5]


In [15]:
na3 = np.array([1,2,3,4,5])
print(np.all(na1 == na2))
print(np.all(na1 == na3))

False
True


In [17]:
na1 = np.arange(6)
na2 = np.arange(6,12)

print("array1 : {}".format(na1))
print("array2 : {}".format(na2))

print("scala : {}".format(na1 * 10))
print("vector : {}".format(na1 * na2))

na3 = na1.reshape(2,3)
na4 = na2.reshape(2,3)

print("array3 : \n{}".format(na3))
print("array4 : \n{}".format(na4))
print("matrix : \n{}".format(na3 * na4))

array1 : [0 1 2 3 4 5]
array2 : [ 6  7  8  9 10 11]
scala : [ 0 10 20 30 40 50]
vector : [ 0  7 16 27 40 55]
array3 : 
[[0 1 2]
 [3 4 5]]
array4 : 
[[ 6  7  8]
 [ 9 10 11]]
matrix : 
[[ 0  7 16]
 [27 40 55]]


In [20]:
na1 = np.arange(12)
na2 = na1.reshape(3,4)
print("na1 : \n{}".format(na1))
print("na2 : \n{}".format(na2))

na3 = np.ones_like(na2)
print("na3 : \n{}".format(na3))

na1 : 
[ 0  1  2  3  4  5  6  7  8  9 10 11]
na2 : 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
na3 : 
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [21]:
print("na2 + 1 : \n{}".format(na2+1))         # <- 스칼라에 대해서 broadcasting가능
print("na2 + na3 : \n{}".format(na2 + na3))

na2 + 1 : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
na2 + na3 : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [22]:
na4 = np.arange(4)
print("na2 : \n{}".format(na2))
print("na4 : \n{}".format(na4))

print("na2 + na4 : \n{}".format(na2 + na4))

na5 = np.stack((na4, na4, na4))
print("na5 : \n{}".format(na5))

print("na2 + na5: \n{}".format(na2 + na5))  # <- 행 에 대해서도 broadcasting가능

na2 : 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
na4 : 
[0 1 2 3]
na2 + na4 : 
[[ 0  2  4  6]
 [ 4  6  8 10]
 [ 8 10 12 14]]
na5 : 
[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
na2 + na5: 
[[ 0  2  4  6]
 [ 4  6  8 10]
 [ 8 10 12 14]]


In [31]:
na6 = np.arange(3)[:,np.newaxis]
print("na2 : \n{}".format(na2))
print("na6 : \n{}".format(na6))

print("na2 + na6 : \n{}".format(na2 + na6))

na7 = np.array([[i for _ in range(4)] for i in range(3)])   # <- 이중 for문 돌려서 행렬 만들기 ^^ 기억
print("na7 : \n{}".format(na7))

print("na2 + na7 : \n{}".format(na2 + na7))    # <- 열에 대해서도 broadcasting 성립

na2 : 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
na6 : 
[[0]
 [1]
 [2]]
na2 + na6 : 
[[ 0  1  2  3]
 [ 5  6  7  8]
 [10 11 12 13]]
na7 : 
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]]
na2 + na7 : 
[[ 0  1  2  3]
 [ 5  6  7  8]
 [10 11 12 13]]


In [ ]:
function 스킵~~~~