In [1]:
import numpy as np

In [2]:
na = np.array([-1, 0, 1, 2, 3.8])
print(na)

na = na.astype(int)
print(na)

na = na.astype(bool)
print(na)

na = na.astype(str)   #<--- 0 은 false로 인식하니까
print(na)

[-1.   0.   1.   2.   3.8]
[-1  0  1  2  3]
[ True False  True  True  True]
['True' 'False' 'True' 'True' 'True']


In [3]:
na = np.random.rand(5,5)
print(na)

na = (na*6+5).astype(int)
print(na)

[[ 0.33874929  0.9454654   0.97676642  0.2131035   0.01280265]
 [ 0.4570149   0.74653104  0.35657296  0.81955923  0.10759347]
 [ 0.03994721  0.09707737  0.25230774  0.62838644  0.20026971]
 [ 0.09257374  0.26906633  0.03052237  0.86055309  0.62271706]
 [ 0.82250374  0.16516627  0.06820254  0.99062731  0.36403765]]
[[ 7 10 10  6  5]
 [ 7  9  7  9  5]
 [ 5  5  6  8  6]
 [ 5  6  5 10  8]
 [ 9  5  5 10  7]]
