### Quiz  - 1/28까지 풀어서 매니저님/강사님 제출

In [1]:
import numpy as np

##### 1. 5개의 1로 이루어진 정수데이터 타입의 벡터를 만드세요

In [2]:
na_1 = np.ones(5).astype(int)
na_1

array([1, 1, 1, 1, 1])

##### 2. 10개의 1로 이루어진 정수 데이터 타입의 벡터에서 마지막 3개의 데이터는 5가 들어있는 벡터를 만드세요

In [3]:
na_2 = np.ones(10).astype(int)
na_2[7:] = 5
na_2

array([1, 1, 1, 1, 1, 1, 1, 5, 5, 5])

##### 3. 10에서 20까지의 데이터를 가지는 벡터를 만드세요  (arrange사용)

In [4]:
na_3 = np.arange(10,20+1)
na_3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

##### 4. 위 벡터의 순서를 바꾸세요

In [5]:
na_4 = na_3[::-1]
na_4

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

##### 5. 0부터 8까지의 값을 가지는 3x3 행렬을 만드세요

In [6]:
na_5 = np.arange(8+1).reshape(3,3)
na_5

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

##### 6. 위의 벡터에서  `[[4,5],[7,8]]`  행렬을 만드세요

In [7]:
na_6 = na_5[1:,1:]
na_6

array([[4, 5],
       [7, 8]])

##### 7. 1에서 10까지의 데이터를 랜덤하게 가지는 3*4 행렬을 만드세요

In [8]:
na_7 = np.random.randint(1,10+1, (3,4))
na_7

array([[10,  8,  1,  9],
       [ 9,  4,  4,  1],
       [ 1,  9,  4, 10]])

##### 8. 위에서 만든 행렬의 unique 한 숫자들 리스트와 각숫자의 갯수를 리스트로 나타내세요

In [9]:
na_8_index, na_8_count = np.unique(na_7, return_counts = True)
na_8_index, na_8_count

(array([ 1,  4,  8,  9, 10]), array([3, 3, 1, 3, 2]))

##### 9. 1에서 12까지에 숫자가 들어간 3*4 행렬을 만드시고 행과 열에 관계없이 데이터를 섞으세요

In [10]:
na_9 = np.arange(1,12+1).reshape(3,4)
np.random.shuffle(na_9)
na_9

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

##### 10. 1부터 10까지의 랜덤한 데이터가 들어가는 `3*3`행렬을 만드시고 가장 아래에 위의 데이터를 모두 합한 `1*3`행렬을 추가해서 `4*3`행렬을 만드세요

In [11]:
na_10_1 = np.random.randint(1,10+1, size=(3,3))
na_10_1

array([[ 2,  7,  6],
       [ 3,  3,  4],
       [ 7, 10,  5]])

In [12]:
na_10_2 = np.vstack((na_10_1, na_10_1.sum(axis=0)))
na_10_2

array([[ 2,  7,  6],
       [ 3,  3,  4],
       [ 7, 10,  5],
       [12, 20, 15]])

##### 11. 10번문제의 결과로 나온 행렬데이터에서 평균값을 출력하고 평균값보다 큰 숫자들만 유니크한 리스트로 나열하세요 (평균값은 소수 둘째 자리까지만 나타내세요)

In [25]:
na_11_1 = na_10_2.mean()
na_11_1

7.833333333333333

In [26]:
print(np.unique(na_10_2[na_10_2 > na_11_1]))

[10 12 15 20]


In [24]:
avg = na_10_2.mean()
na_11 = na_10_2[na_10_2 > avg]
print("avg : ", round(avg, 2))
print(np.unique(na_11))

avg :  7.83
[10 12 15 20]


##### 12. 1부터 20까지의 랜덤숫자를 가지는 5*5 행렬을 만드시고 최대값에는 숫자(MAX), 최소값에는 숫자(MIN)으로 행렬을 바꾸세요

In [16]:
na_12 = np.random.randint(1,20+1,(5,5))
na_12

array([[ 1, 14,  5, 17, 10],
       [10, 12,  3,  7, 17],
       [16, 11, 15, 15,  3],
       [ 2, 19, 14,  5, 18],
       [ 7, 15, 17, 17,  7]])

In [17]:
max, min = np.max(na_12), np.min(na_12)
max, min

(19, 1)

In [18]:
### 바꿔야 하는 기준을 지정 -> 행렬의 값 = 조건 이라는 식으로 idx할당 가능.
max_idx = na_12 == max
min_idx = na_12 == min

In [19]:
na_12 = na_12.astype("str")
na_12[max_idx] = str(max) + "(MAX)"
na_12[min_idx] = str(min) + "(MIN)"
na_12

array([['1(MIN)', '14', '5', '17', '10'],
       ['10', '12', '3', '7', '17'],
       ['16', '11', '15', '15', '3'],
       ['2', '19(MAX)', '14', '5', '18'],
       ['7', '15', '17', '17', '7']],
      dtype='<U21')

##### 13. 100에서 130까지의 랜덤 숫자를 가지는 8*8행렬을 만드시고 3의 배수에는 fiz, 5의 배수에는 buz, 3과 5의 배수는 fbz 문자를 출력하세요

In [20]:
na_13 = np.random.randint(100, 130+1, (8,8))
na_13

array([[116, 130, 106, 116, 125, 121, 125, 121],
       [106, 107, 123, 119, 104, 114, 129, 124],
       [114, 104, 123, 123, 118, 103, 102, 102],
       [112, 115, 102, 107, 124, 124, 117, 110],
       [104, 111, 129, 121, 118, 124, 108, 115],
       [116, 111, 108, 120, 102, 130, 127, 101],
       [117, 115, 130, 126, 101, 102, 102, 121],
       [105, 100, 129, 114, 103, 129, 103, 119]])

In [21]:
### 바꿔야 하는 기준을 지정 -> 행렬의 값 = 조건 이라는 식으로 idx할당 가능.
idx_3 = na_13 % 3 == 0
idx_5 = na_13 % 5 == 0
idx_15 = na_13 % 15 == 0

In [22]:
na_13 = na_13.astype("str")
na_13[idx_3] = "fiz"
na_13[idx_5] = "buz"
na_13[idx_15] = "fbz"
na_13

array([['116', 'buz', '106', '116', 'buz', '121', 'buz', '121'],
       ['106', '107', 'fiz', '119', '104', 'fiz', 'fiz', '124'],
       ['fiz', '104', 'fiz', 'fiz', '118', '103', 'fiz', 'fiz'],
       ['112', 'buz', 'fiz', '107', '124', '124', 'fiz', 'buz'],
       ['104', 'fiz', 'fiz', '121', '118', '124', 'fiz', 'buz'],
       ['116', 'fiz', 'fiz', 'fbz', 'fiz', 'buz', '127', '101'],
       ['fiz', 'buz', 'buz', 'fiz', '101', 'fiz', 'fiz', '121'],
       ['fbz', 'buz', 'fiz', 'fiz', '103', 'fiz', '103', '119']],
      dtype='<U21')

##### 14. 리스트 컴프리헨션을 이용하여 아래와 같은 규칙은 갖는 행렬을 만드세요

In [23]:
number = 7
na_14 = np.array([[i*j for j in range(1,number+1)] for i in range(1, number+1)])
print("number :", number)
na_14

number : 7


array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 2,  4,  6,  8, 10, 12, 14],
       [ 3,  6,  9, 12, 15, 18, 21],
       [ 4,  8, 12, 16, 20, 24, 28],
       [ 5, 10, 15, 20, 25, 30, 35],
       [ 6, 12, 18, 24, 30, 36, 42],
       [ 7, 14, 21, 28, 35, 42, 49]])