##### 1_make

In [ ]:
### array

In [1]:
array = np.array([0,1,2,3,4,5])
print(type(array))
print(array)

<class 'numpy.ndarray'>
[0 1 2 3 4 5]


In [2]:
array = np.array([[0],[1],[2]])
print(array, array.shape)

[[0]
 [1]
 [2]] (3, 1)


In [3]:
array = np.array([
    [0,1,2],
    [3,4,5]
])
print(array)

[[0 1 2]
 [3 4 5]]


In [4]:
array = np.array([
    [[0,1,2,3],
     [4,5,6,7],
     [8,9,10,11]],
    [[0,1,2,3],
     [4,5,100,7],
     [8,9,10,11]]
])
print(array)
print(array.ndim, array.shape)

[[[  0   1   2   3]
  [  4   5   6   7]
  [  8   9  10  11]]

 [[  0   1   2   3]
  [  4   5 100   7]
  [  8   9  10  11]]]
3 (2, 3, 4)


In [5]:
na = np.array([1,2,3,4,5,6,7,8])
na.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
rna = np.reshape(na,(4,2))
rna

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [8]:
rna.T

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

In [9]:
array

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[  0,   1,   2,   3],
        [  4,   5, 100,   7],
        [  8,   9,  10,  11]]])

In [10]:
print(array[1][1][2])
print(array[1,1,2])

100
100


In [11]:
result = array[1:,1:,2:]
print(result)
print(result.ndim, result.shape)

[[[100   7]
  [ 10  11]]]
3 (1, 2, 2)


In [13]:
z = np.zeros(5)
print(z)
print(z.ndim, z.shape)

[ 0.  0.  0.  0.  0.]
1 (5,)


In [14]:
z = np.zeros([2,3])
print(z)
print(z.ndim, z.shape)

[[ 0.  0.  0.]
 [ 0.  0.  0.]]
2 (2, 3)


In [15]:
z = np.zeros([2,3,4])
print(z)
print(z.ndim, z.shape)

[[[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]]
3 (2, 3, 4)


In [16]:
o = np.ones([2,3,4])
print(o)
print(o.ndim, o.shape)

[[[ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]]]
3 (2, 3, 4)


In [17]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [19]:
array

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[  0,   1,   2,   3],
        [  4,   5, 100,   7],
        [  8,   9,  10,  11]]])

In [20]:
ls = np.ones_like(array)
print(ls)
print(ls.ndim, ls.shape)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
3 (2, 3, 4)


In [21]:
ls = np.zeros_like(array)
print(ls)
print(ls.ndim, ls.shape)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
3 (2, 3, 4)


In [22]:
a = np.empty((5,5))
print(a)

[[  0.00000000e+000   0.00000000e+000   1.08694442e-322   0.00000000e+000
    0.00000000e+000]
 [  1.16095484e-028   3.74168445e+233   1.05879110e+214   2.59345439e+161
    7.35874688e+223]
 [  3.77075687e+233   6.24864985e-085   9.83262436e+247   4.06763159e-144
    6.96410748e+252]
 [  8.03408341e-095   5.72974605e+194   1.16589870e-028   1.47763669e+248
    4.78214477e+180]
 [  1.16441574e-028   5.38669143e+228   7.79350126e-143   3.97084747e+246
    2.03789108e+180]]


In [23]:
 np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [25]:
np.arange(2,10,3)

array([2, 5, 8])

In [27]:
np.arange(2,10+1).reshape(3,3)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [28]:
np.linspace(0, 100, 5)

array([   0.,   25.,   50.,   75.,  100.])

In [29]:
np.linspace(0,100,4)

array([   0.        ,   33.33333333,   66.66666667,  100.        ])

In [30]:
np.logspace(0,100,4)

array([  1.00000000e+000,   2.15443469e+033,   4.64158883e+066,
         1.00000000e+100])

In [31]:
np.random.seed(0)
rd = np.random.rand(10)
rdn = np.random.randn(10)
print(rd)
print(rdn)

[ 0.5488135   0.71518937  0.60276338  0.54488318  0.4236548   0.64589411
  0.43758721  0.891773    0.96366276  0.38344152]
[ 0.14404357  1.45427351  0.76103773  0.12167502  0.44386323  0.33367433
  1.49407907 -0.20515826  0.3130677  -0.85409574]


In [33]:
np.random.seed(1)
rd = np.random.rand(4)
rdn = np.random.randn(4)
print(rd)
print(rdn)

[  4.17022005e-01   7.20324493e-01   1.14374817e-04   3.02332573e-01]
[-0.52817175 -1.07296862  0.86540763 -2.3015387 ]


In [35]:
r = np.random.rand(2,3,4)
print(r)

[[[ 0.69187711  0.31551563  0.68650093  0.83462567]
  [ 0.01828828  0.75014431  0.98886109  0.74816565]
  [ 0.28044399  0.78927933  0.10322601  0.44789353]]

 [[ 0.9085955   0.29361415  0.28777534  0.13002857]
  [ 0.01936696  0.67883553  0.21162812  0.26554666]
  [ 0.49157316  0.05336255  0.57411761  0.14672857]]]


In [38]:
r = np.random.randint(0, 10, (3,3))
print(r)

[[7 7 1]
 [1 3 0]
 [8 6 4]]


In [46]:
np.random.shuffle(r)
r

array([[7, 7, 1],
       [1, 3, 0],
       [8, 6, 4]])

In [47]:
r = np.random.randint(10, size=(3,4))
r

array([[9, 0, 2, 0],
       [7, 1, 7, 9],
       [8, 4, 0, 1]])

In [54]:
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0])

array([2, 3, 3, 0, 0, 3, 3, 2, 2, 3])

In [55]:
na1 = np.arange(6)
na2 = np.arange(6,12)
print(na1, na1.shape)
print(na2, na2.shape)

[0 1 2 3 4 5] (6,)
[ 6  7  8  9 10 11] (6,)


In [59]:
na3 = np.stack((na1, na2)
print(na3, na3.shape)

SyntaxError: invalid syntax (<ipython-input-59-7342aa25c070>, line 2)

In [61]:
na3 = np.stack((na1, na2), axis=-1)
na3

array([[ 0,  6],
       [ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11]])

In [67]:
ls = []
for i in range(5):
    print(range(7), i, i+3)
    print(range(7)[i:i+3])
    print(list(range(7)[i:i+3]), end="\n\n")
    ls.append(list(range(7)[i:i+3]))
ls

range(0, 7) 0 3
range(0, 3)
[0, 1, 2]

range(0, 7) 1 4
range(1, 4)
[1, 2, 3]

range(0, 7) 2 5
range(2, 5)
[2, 3, 4]

range(0, 7) 3 6
range(3, 6)
[3, 4, 5]

range(0, 7) 4 7
range(4, 7)
[4, 5, 6]



[[0, 1, 2], [1, 2, 3], [2, 3, 4], [3, 4, 5], [4, 5, 6]]

In [72]:
a = np.vstack(ls)
print(a)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]


In [73]:
b = np.hstack(ls)
print(b)

[0 1 2 1 2 3 2 3 4 3 4 5 4 5 6]


In [75]:
c = np.stack(ls, axis=-1)
print(c)

[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]]


In [76]:
data = [list(range(7)[i:i+3])for i in range(5)]
print(data)
np.stack(data, axis=-1)

[[0, 1, 2], [1, 2, 3], [2, 3, 4], [3, 4, 5], [4, 5, 6]]


array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [77]:
np.arange(5)[:,np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [78]:
r1 = np.random.randint(10, size=(2,3))
print(r1)

[[6 7 3]
 [5 3 2]]


In [79]:
r2 = np.random.randint(20, size=(5,3))
print(r2)

[[ 4  4  0]
 [19  3 19]
 [ 5  6 15]
 [ 7  5 15]
 [17  0 10]]


In [80]:
r3 = np.random.randint(30, size=(2,5))
print(r3)

[[10  2 24  2 17]
 [ 4  0 28 20 14]]


In [83]:
# concat: 가로축 결합 (axis=0)

r4 = np.concatenate([r1, r2])
r4

array([[ 6,  7,  3],
       [ 5,  3,  2],
       [ 4,  4,  0],
       [19,  3, 19],
       [ 5,  6, 15],
       [ 7,  5, 15],
       [17,  0, 10]])

In [85]:
r5 = np.concatenate([r1, r3], axis=1)
r5

array([[ 6,  7,  3, 10,  2, 24,  2, 17],
       [ 5,  3,  2,  4,  0, 28, 20, 14]])

In [86]:
r = np.arange(0,10)
r

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
r1 = np.split(r, [5])
r1

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [88]:
r1, r2 = np.split(r, [5])
r1, r2

(array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]))

In [89]:
r1, r2, r3, r4, r5 = np.split(r, [2,4,6,8])
r1, r2, r3, r4, r5

(array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9]))

In [90]:
r = np.random.randint(10, size=(4,6))
r

array([[1, 7, 3, 1, 6, 6],
       [9, 6, 9, 6, 0, 0],
       [2, 9, 6, 0, 6, 7],
       [0, 3, 9, 0, 3, 4]])

In [92]:
r1, r2 = np.vsplit(r, [2])
print(r1)
print(r2)

[[1 7 3 1 6 6]
 [9 6 9 6 0 0]]
[[2 9 6 0 6 7]
 [0 3 9 0 3 4]]


In [93]:
r1, r2 = np.hsplit(r, [3])
print(r1)
print(r2)

[[1 7 3]
 [9 6 9]
 [2 9 6]
 [0 3 9]]
[[1 6 6]
 [6 0 0]
 [0 6 7]
 [0 3 4]]


In [94]:
r1, r2, r3 = np.hsplit(r, [2,4])
print(r1)
print(r2)
print(r3)

[[1 7]
 [9 6]
 [2 9]
 [0 3]]
[[3 1]
 [9 6]
 [6 0]
 [9 0]]
[[6 6]
 [0 0]
 [6 7]
 [3 4]]


In [102]:
r1 = np.random.randint(10, size=(3,3))
print(r1)

[[7 5 3]
 [8 8 0]
 [6 7 9]]


In [104]:
r1.sort()
r1

array([[3, 5, 7],
       [0, 8, 8],
       [6, 7, 9]])

In [105]:
r1.sort(axis=0)
r1

array([[0, 5, 7],
       [3, 7, 8],
       [6, 8, 9]])

In [ ]:
# 문제
# 1~9까지의 숫자가 들어가는 3*3 행렬을 만드세요
# 만든 행렬을 무작위로 섞으세요

In [109]:
a = np.random.randint(1,10, size=(3,3))
a

array([[8, 8, 3],
       [7, 1, 6],
       [3, 2, 9]])

In [118]:
np.random.shuffle(a)
a

array([[7, 1, 6],
       [3, 2, 9],
       [8, 8, 3]])